//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitWebServiceConsole.GitWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GitWebService.IGitWebService")]
    public interface IGitWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGitWebService/GetNumber", ReplyAction="http://tempuri.org/IGitWebService/GetNumberResponse")]
        int GetNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGitWebService/GetNumber", ReplyAction="http://tempuri.org/IGitWebService/GetNumberResponse")]
        System.Threading.Tasks.Task<int> GetNumberAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGitWebServiceChannel : GitWebServiceConsole.GitWebService.IGitWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GitWebServiceClient : System.ServiceModel.ClientBase<GitWebServiceConsole.GitWebService.IGitWebService>, GitWebServiceConsole.GitWebService.IGitWebService {
        
        public GitWebServiceClient() {
        }
        
        public GitWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GitWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GitWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GitWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetNumber() {
            return base.Channel.GetNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberAsync() {
            return base.Channel.GetNumberAsync();
        }
    }
}
